set guifont=FiraCode\ Nerd\ Font\ Mono:h18
set guifont=Hack\ Nerd\ Font:h18
set guifont=Noto\ Color\ Emoji:h18
set guifont=FantasqueSansMono\ Nerd\ Font\ Mono:h18
let g:neovide_refresh_rate=30
let g:neovide_no_idle=v:true
let g:neovide_cursor_trail_length=0.15
let g:neovide_fullscreen=v:false
let g:neovide_cursor_vfx_mode = "railgun"
" let g:neovide_cursor_vfx_mode = "wireframe"
let g:neovide_cursor_vfx_particle_lifetime=10
let g:neovide_cursor_vfx_particle_curl=0.5
